# Create a RadosGW account (ID auto-generated by RadosGW)
resource "radosgw_iam_account" "example" {
  name  = "example-account"
  email = "account@example.com"
}

# Create an account with an explicit ID and limits
resource "radosgw_iam_account" "custom" {
  account_id      = "RGW00000000000000001"
  name            = "custom-account"
  email           = "custom@example.com"
  max_users       = 100
  max_roles       = 25
  max_buckets     = 500
  max_access_keys = 8
}

# Create the account together with its root (admin) user
resource "radosgw_iam_account" "team" {
  name = "team-account"
}

resource "radosgw_iam_user" "team_root" {
  user_id      = "team-root"
  display_name = "TeamRootUser"
  account_id   = radosgw_iam_account.team.account_id
  account_root = true
}
