package provider

import (
	"fmt"
	"strings"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"
)

func TestAccRadosgwIAMAccount_basic(t *testing.T) {
	t.Parallel()

	accountID := "RGW" + randomAccountID()
	accountName := randomName("account")

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheckSkipForVersion(t, CephVersion_Squid) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckRadosgwIAMAccountDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccRadosgwIAMAccountConfig_basic(accountID, accountName),
				Check: resource.ComposeTestCheckFunc(
					testAccCheckRadosgwIAMAccountExists("radosgw_iam_account.test"),
					resource.TestCheckResourceAttr("radosgw_iam_account.test", "account_id", accountID),
					resource.TestCheckResourceAttr("radosgw_iam_account.test", "name", accountName),
					resource.TestCheckResourceAttr("radosgw_iam_account.test", "max_users", "-1"),
					resource.TestCheckResourceAttr("radosgw_iam_account.test", "max_buckets", "1000"),
				),
			},
			{
				ResourceName:                         "radosgw_iam_account.test",
				ImportState:                          true,
				ImportStateVerify:                    true,
				ImportStateId:                        accountID,
				ImportStateVerifyIdentifierAttribute: "account_id",
			},
		},
	})
}

func TestAccRadosgwIAMAccount_withEmail(t *testing.T) {
	t.Parallel()

	accountID := "RGW" + randomAccountID()
	accountName := randomName("account")
	email := randomEmail()

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheckSkipForVersion(t, CephVersion_Squid) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckRadosgwIAMAccountDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccRadosgwIAMAccountConfig_withEmail(accountID, accountName, email),
				Check: resource.ComposeTestCheckFunc(
					testAccCheckRadosgwIAMAccountExists("radosgw_iam_account.test"),
					resource.TestCheckResourceAttr("radosgw_iam_account.test", "account_id", accountID),
					resource.TestCheckResourceAttr("radosgw_iam_account.test", "name", accountName),
					resource.TestCheckResourceAttr("radosgw_iam_account.test", "email", email),
				),
			},
		},
	})
}

func TestAccRadosgwIAMAccount_withLimits(t *testing.T) {
	t.Parallel()

	accountID := "RGW" + randomAccountID()
	accountName := randomName("account")
	maxUsers := int64(100)
	maxBuckets := int64(50)
	maxRoles := int64(25)

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheckSkipForVersion(t, CephVersion_Squid) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckRadosgwIAMAccountDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccRadosgwIAMAccountConfig_withLimits(accountID, accountName, maxUsers, maxBuckets, maxRoles),
				Check: resource.ComposeTestCheckFunc(
					testAccCheckRadosgwIAMAccountExists("radosgw_iam_account.test"),
					resource.TestCheckResourceAttr("radosgw_iam_account.test", "account_id", accountID),
					resource.TestCheckResourceAttr("radosgw_iam_account.test", "name", accountName),
					resource.TestCheckResourceAttr("radosgw_iam_account.test", "max_users", "100"),
					resource.TestCheckResourceAttr("radosgw_iam_account.test", "max_buckets", "50"),
					resource.TestCheckResourceAttr("radosgw_iam_account.test", "max_roles", "25"),
				),
			},
			{
				Config: testAccRadosgwIAMAccountConfig_withLimits(accountID, accountName+"-updated", 200, 100, 50),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("radosgw_iam_account.test", "name", accountName+"-updated"),
					resource.TestCheckResourceAttr("radosgw_iam_account.test", "max_users", "200"),
					resource.TestCheckResourceAttr("radosgw_iam_account.test", "max_buckets", "100"),
					resource.TestCheckResourceAttr("radosgw_iam_account.test", "max_roles", "50"),
				),
			},
		},
	})
}

func TestAccRadosgwIAMAccount_autoGeneratedID(t *testing.T) {
	t.Parallel()

	accountName := randomName("account")

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheckSkipForVersion(t, CephVersion_Squid) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckRadosgwIAMAccountDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccRadosgwIAMAccountConfig_autoGenerated(accountName),
				Check: resource.ComposeTestCheckFunc(
					testAccCheckRadosgwIAMAccountExists("radosgw_iam_account.test"),
					resource.TestCheckResourceAttrSet("radosgw_iam_account.test", "account_id"),
					resource.TestCheckResourceAttr("radosgw_iam_account.test", "name", accountName),
				),
			},
			{
				ResourceName:                         "radosgw_iam_account.test",
				ImportState:                          true,
				ImportStateVerify:                    true,
				ImportStateVerifyIdentifierAttribute: "account_id",
				ImportStateIdFunc:                    testAccRadosgwIAMAccountImportStateIDFunc("radosgw_iam_account.test"),
			},
		},
	})
}

func testAccCheckRadosgwIAMAccountDestroy(s *terraform.State) error {
	if testAccAdminClient == nil {
		return nil
	}

	for name, rs := range s.RootModule().Resources {
		if rs.Type != "radosgw_iam_account" || strings.HasPrefix(name, "data.") {
			continue
		}

		accountID := rs.Primary.Attributes["account_id"]
		_, err := testAccAdminClient.GetAccount(testCtx, accountID)
		if err == nil {
			return fmt.Errorf("Account %s still exists", accountID)
		}
		if !isAccountNotFoundError(err) {
			return fmt.Errorf("Error checking for account %s: %w", accountID, err)
		}
	}
	return nil
}

func testAccCheckRadosgwIAMAccountExists(resourceName string) resource.TestCheckFunc {
	return func(s *terraform.State) error {
		rs, ok := s.RootModule().Resources[resourceName]
		if !ok {
			return fmt.Errorf("Resource not found: %s", resourceName)
		}

		accountID := rs.Primary.Attributes["account_id"]
		if accountID == "" {
			return fmt.Errorf("Resource ID not set")
		}

		if testAccAdminClient == nil {
			return nil
		}

		_, err := testAccAdminClient.GetAccount(testCtx, accountID)
		if err != nil {
			return fmt.Errorf("Error getting account: %w", err)
		}

		return nil
	}
}

func testAccRadosgwIAMAccountImportStateIDFunc(resourceName string) resource.ImportStateIdFunc {
	return func(s *terraform.State) (string, error) {
		rs, ok := s.RootModule().Resources[resourceName]
		if !ok {
			return "", fmt.Errorf("resource not found: %s", resourceName)
		}
		id := rs.Primary.Attributes["account_id"]
		if id == "" {
			return "", fmt.Errorf("account_id not set in state for %s", resourceName)
		}
		return id, nil
	}
}

func testAccRadosgwIAMAccountConfig_basic(accountID, name string) string {
	return providerConfig() + fmt.Sprintf(`
resource "radosgw_iam_account" "test" {
  account_id = %q
  name       = %q
}
`, accountID, name)
}

func testAccRadosgwIAMAccountConfig_withEmail(accountID, name, email string) string {
	return providerConfig() + fmt.Sprintf(`
resource "radosgw_iam_account" "test" {
  account_id = %q
  name       = %q
  email      = %q
}
`, accountID, name, email)
}

func testAccRadosgwIAMAccountConfig_withLimits(accountID, name string, maxUsers, maxBuckets, maxRoles int64) string {
	return providerConfig() + fmt.Sprintf(`
resource "radosgw_iam_account" "test" {
  account_id  = %q
  name        = %q
  max_users   = %d
  max_buckets = %d
  max_roles   = %d
}
`, accountID, name, maxUsers, maxBuckets, maxRoles)
}

func testAccRadosgwIAMAccountConfig_autoGenerated(name string) string {
	return providerConfig() + fmt.Sprintf(`
resource "radosgw_iam_account" "test" {
  name = %q
}
`, name)
}
