package provider

import (
	"context"
	"encoding/xml"
	"errors"
	"fmt"
	"net/url"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &IAMAccountAccessKeyResource{}
var _ resource.ResourceWithImportState = &IAMAccountAccessKeyResource{}

func NewIAMAccountAccessKeyResource() resource.Resource {
	return &IAMAccountAccessKeyResource{}
}

// IAMAccountAccessKeyResource manages an access key for a user within a RadosGW
// account through the IAM API (CreateAccessKey), as opposed to the Admin-Ops
// based radosgw_iam_access_key.
type IAMAccountAccessKeyResource struct {
	client    *RadosgwClient
	iamClient *IAMClient
}

type IAMAccountAccessKeyResourceModel struct {
	User       types.String `tfsdk:"user"`
	Status     types.String `tfsdk:"status"`
	AccessKey  types.String `tfsdk:"access_key"`
	SecretKey  types.String `tfsdk:"secret_key"`
	CreateDate types.String `tfsdk:"create_date"`
}

type createAccessKeyResponseXML struct {
	XMLName xml.Name `xml:"CreateAccessKeyResponse"`
	Result  struct {
		AccessKey struct {
			UserName        string `xml:"UserName"`
			AccessKeyId     string `xml:"AccessKeyId"`
			Status          string `xml:"Status"`
			SecretAccessKey string `xml:"SecretAccessKey"`
			CreateDate      string `xml:"CreateDate"`
		} `xml:"AccessKey"`
	} `xml:"CreateAccessKeyResult"`
}

// iamStatusToAPI maps the lowercase schema value to the IAM API's capitalized form.
func iamStatusToAPI(status string) string {
	if strings.EqualFold(status, "inactive") {
		return "Inactive"
	}
	return "Active"
}

func (r *IAMAccountAccessKeyResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_iam_account_access_key"
}

func (r *IAMAccountAccessKeyResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages an access key for a user **within a RadosGW account**, using the S3/IAM API " +
			"(`CreateAccessKey`) rather than the Admin Ops API.\n\n" +
			"Use this together with `radosgw_iam_account_user`: it lets an **account root** — or a member holding " +
			"an IAM policy granting `iam:CreateAccessKey` (e.g. for self-service keys) — issue S3 credentials " +
			"**without any admin capabilities**. For admin-managed RGW users (with Swift keys, custom key values, " +
			"etc.) use `radosgw_iam_access_key` instead.\n\n" +
			"~> **Note:** Unlike `radosgw_iam_access_key`, the key pair is **generated by RadosGW** — you cannot " +
			"supply your own `access_key`/`secret_key`. The `secret_key` is only returned when the key is created; " +
			"it cannot be recovered later (including on import).",

		Attributes: map[string]schema.Attribute{
			"user": schema.StringAttribute{
				MarkdownDescription: "The IAM user (name) that the access key belongs to.",
				Required:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"status": schema.StringAttribute{
				MarkdownDescription: "The status of the access key: `active` (default) or `inactive`.",
				Optional:            true,
				Computed:            true,
				Default:             stringdefault.StaticString("active"),
				Validators: []validator.String{
					stringvalidator.OneOf("active", "inactive"),
				},
			},
			"access_key": schema.StringAttribute{
				MarkdownDescription: "The generated access key ID.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"secret_key": schema.StringAttribute{
				MarkdownDescription: "The generated secret access key. Only available at creation time; null on import.",
				Computed:            true,
				Sensitive:           true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"create_date": schema.StringAttribute{
				MarkdownDescription: "The date and time the access key was created, in RFC 3339 format.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

func (r *IAMAccountAccessKeyResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*RadosgwClient)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *RadosgwClient, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}

	r.client = client
	r.iamClient = newAccountIAMClient(client)
}

func (r *IAMAccountAccessKeyResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan IAMAccountAccessKeyResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	user := plan.User.ValueString()

	params := url.Values{}
	params.Set("Action", "CreateAccessKey")
	params.Set("UserName", user)

	body, err := r.iamClient.DoRequest(ctx, params, "iam")
	if err != nil {
		resp.Diagnostics.AddError(
			"Error Creating IAM Account Access Key",
			fmt.Sprintf("Could not create access key for user %s: %s", user, err.Error()),
		)
		return
	}

	var response createAccessKeyResponseXML
	if err := xml.Unmarshal(body, &response); err != nil {
		resp.Diagnostics.AddError(
			"Error Parsing Response",
			fmt.Sprintf("Could not parse CreateAccessKey response: %s", err.Error()),
		)
		return
	}

	key := response.Result.AccessKey
	plan.AccessKey = types.StringValue(key.AccessKeyId)
	plan.SecretKey = types.StringValue(key.SecretAccessKey)
	plan.CreateDate = types.StringValue(key.CreateDate)

	// New keys are created Active; apply a requested inactive status.
	if strings.EqualFold(plan.Status.ValueString(), "inactive") {
		if err := r.updateStatus(ctx, user, key.AccessKeyId, "inactive"); err != nil {
			resp.Diagnostics.AddError(
				"Error Setting Access Key Status",
				fmt.Sprintf("Key %s was created but its status could not be set to inactive: %s", key.AccessKeyId, err.Error()),
			)
			return
		}
		plan.Status = types.StringValue("inactive")
	} else {
		plan.Status = types.StringValue(strings.ToLower(key.Status))
	}

	tflog.Trace(ctx, "Created IAM account access key", map[string]any{"user": user, "access_key": key.AccessKeyId})

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *IAMAccountAccessKeyResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state IAMAccountAccessKeyResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	user := state.User.ValueString()
	keyID := state.AccessKey.ValueString()

	keys, err := iamListAccessKeys(ctx, r.iamClient, user)
	if err != nil {
		if errors.Is(err, ErrNoSuchEntity) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError(
			"Error Reading IAM Account Access Key",
			fmt.Sprintf("Could not list access keys for user %s: %s", user, err.Error()),
		)
		return
	}

	var found *iamAccessKeyMetadataXML
	for i := range keys {
		if keys[i].AccessKeyId == keyID {
			found = &keys[i]
			break
		}
	}
	if found == nil {
		tflog.Info(ctx, "IAM account access key not found, removing from state", map[string]any{
			"user": user, "access_key": keyID,
		})
		resp.State.RemoveResource(ctx)
		return
	}

	state.Status = types.StringValue(strings.ToLower(found.Status))
	if found.CreateDate != "" {
		state.CreateDate = types.StringValue(found.CreateDate)
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *IAMAccountAccessKeyResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state IAMAccountAccessKeyResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if !strings.EqualFold(plan.Status.ValueString(), state.Status.ValueString()) {
		if err := r.updateStatus(ctx, state.User.ValueString(), state.AccessKey.ValueString(), plan.Status.ValueString()); err != nil {
			resp.Diagnostics.AddError(
				"Error Updating Access Key Status",
				fmt.Sprintf("Could not set status of key %s: %s", state.AccessKey.ValueString(), err.Error()),
			)
			return
		}
	}

	// Carry the computed values forward (only status is mutable).
	plan.AccessKey = state.AccessKey
	plan.SecretKey = state.SecretKey
	plan.CreateDate = state.CreateDate

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *IAMAccountAccessKeyResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state IAMAccountAccessKeyResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	params := url.Values{}
	params.Set("Action", "DeleteAccessKey")
	params.Set("UserName", state.User.ValueString())
	params.Set("AccessKeyId", state.AccessKey.ValueString())

	_, err := r.iamClient.DoRequest(ctx, params, "iam")
	if err != nil {
		if errors.Is(err, ErrNoSuchEntity) {
			return
		}
		resp.Diagnostics.AddError(
			"Error Deleting IAM Account Access Key",
			fmt.Sprintf("Could not delete access key %s: %s", state.AccessKey.ValueString(), err.Error()),
		)
		return
	}

	tflog.Trace(ctx, "Deleted IAM account access key", map[string]any{
		"user": state.User.ValueString(), "access_key": state.AccessKey.ValueString(),
	})
}

// ImportState imports an access key using the "user:access_key" identifier.
// The secret cannot be recovered and will be null after import.
func (r *IAMAccountAccessKeyResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.SplitN(req.ID, ":", 2)
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		resp.Diagnostics.AddError(
			"Invalid Import ID",
			fmt.Sprintf("Expected import ID in the form \"user:access_key\", got %q.", req.ID),
		)
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("user"), parts[0])...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("access_key"), parts[1])...)
}

// updateStatus sets an access key's status (active/inactive) via UpdateAccessKey.
func (r *IAMAccountAccessKeyResource) updateStatus(ctx context.Context, user, keyID, status string) error {
	params := url.Values{}
	params.Set("Action", "UpdateAccessKey")
	params.Set("UserName", user)
	params.Set("AccessKeyId", keyID)
	params.Set("Status", iamStatusToAPI(status))
	_, err := r.iamClient.DoRequest(ctx, params, "iam")
	return err
}
